script:
  - "bundle exec rubocop"
  - "bundle exec rake neo4j:install[$NEO4J_VERSION] neo4j:disable_auth neo4j:start default --trace"
language: ruby
rvm:
  - 2.2.2
  - 2.1.5
  - jruby-1.7.18
  - rbx-2.5.8
  # - jruby-19mode
env:
  # - NEO4J_VERSION=community-latest
  - NEO4J_VERSION=community-2.3.0-M03
  - NEO4J_VERSION=community-2.2.3
  - NEO4J_VERSION=community-2.1.8
sudo: false