script:
  - "bundle exec rubocop"
  - "bundle exec rake neo4j:install[$NEO4J_VERSION] neo4j:disable_auth neo4j:start --trace && rspec --tag $RSPEC_TAGS"
language: ruby
rvm:
  - 2.2.3
  - 2.1.5
  - jruby-1.7.20
  - jruby-9.0.0.0
env:
  - RSPEC_TAGS=~new_cypher_session NEO4J_VERSION=community-2.2.5
sudo: false
matrix:
  include:
    # Pre-2.1.5 is special, metadata isn't sent back with HTTP REST endpoint
    - rvm: 2.2.3
      env: RSPEC_TAGS=~new_cypher_session NEO4J_VERSION=community-2.1.4

    # Sanity check against Neo4j 2.3.x with MRI and JRuby
    - rvm: 2.2.3
      env: RSPEC_TAGS=~new_cypher_session NEO4J_VERSION=community-2.3.0-M03
    - rvm: jruby-9.0.0.0
      env: RSPEC_TAGS=~new_cypher_session NEO4J_VERSION=community-2.3.0-M03

    # Testing new CypherSession
    - rvm: 2.2.3
      env: RSPEC_TAGS=new_cypher_session NEO4J_VERSION=community-2.2.5
    - rvm: 2.2.3
      env: RSPEC_TAGS=new_cypher_session NEO4J_VERSION=community-2.1.4
    - rvm: jruby-9.0.0.0
      env: RSPEC_TAGS=new_cypher_session NEO4J_VERSION=community-2.2.5
