script:
  - "bundle exec rubocop"
  - "bundle exec rake neo4j:install[$NEO4J_VERSION] neo4j:disable_auth neo4j:start --trace && rspec --tag $RSPEC_TAGS"
language: ruby
rvm:
  - 2.2.3
  - 2.1.5
  - jruby-1.7.18
env:
  - RSPEC_TAGS=~new_cypher_session NEO4J_VERSION=community-2.3.0-M03
  - RSPEC_TAGS=~new_cypher_session NEO4J_VERSION=community-2.2.5
  - RSPEC_TAGS=~new_cypher_session NEO4J_VERSION=community-2.1.4 # Pre-2.1.5 is special!
sudo: false
matrix:
  include:
    - rvm: jruby-1.7.18
      env: RSPEC_TAGS=new_cypher_session NEO4J_VERSION=community-2.1.4
    - rvm: jruby-1.7.18
      env: RSPEC_TAGS=new_cypher_session NEO4J_VERSION=community-2.2.5
